#define GRANDOTE_VINTAGE_PRODUCT "Grandote"
#define GRANDOTE_VINTAGE_RELEASE "hawkeye"
#define GRANDOTE_VINTAGE_VERSION "7.0.0"
#define GRANDOTE_VINTAGE_COPYRIGHT "Copyright 2005-2011 Digital Aggregates Corporation, Colorado, USA."
#define GRANDOTE_VINTAGE_CONTACT "coverclock@diag.com (Chip Overclock)"
#define GRANDOTE_VINTAGE_URL "http://www.diag.com/navigation/downloads/Desperadito.html"
#define GRANDOTE_VINTAGE_DATE "20111223T144844.477531708-07:00"
#define GRANDOTE_VINTAGE_PLATFORM "Linux"
#define GRANDOTE_VINTAGE_TARGET "IA32"
#define GRANDOTE_VINTAGE_LICENSE "Modified GNU Lesser Public License"
